<?php

declare(strict_types=1);

return [
    'name' => 'SIYADI',
    'full_name' => 'Sistem Informasi Yayasan Dejiaohui Indonesia',
    'default_branch' => 'SBY',
    'modules' => [
        'members' => [
            'title' => 'Anggota', 'icon' => '👥', 'table' => 'members',
            'search' => ['member_no', 'name', 'phone', 'email'],
            'columns' => ['member_no' => 'No. Anggota', 'name' => 'Nama', 'phone' => 'Telepon', 'status' => 'Status'],
            'fields' => [
                'member_no' => ['label' => 'Nomor Anggota', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama Lengkap', 'type' => 'text', 'required' => true],
                'chinese_name' => ['label' => 'Nama Tionghoa', 'type' => 'text'],
                'gender' => ['label' => 'Jenis Kelamin', 'type' => 'select', 'options' => ['Laki-laki', 'Perempuan'], 'required' => true],
                'phone' => ['label' => 'Nomor Telepon', 'type' => 'text'],
                'email' => ['label' => 'Email', 'type' => 'email'],
                'address' => ['label' => 'Alamat', 'type' => 'textarea'],
                'join_date' => ['label' => 'Tanggal Bergabung', 'type' => 'date'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Aktif', 'Tidak Aktif'], 'required' => true],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'donors' => [
            'title' => 'Donatur', 'icon' => '🤝', 'table' => 'donors',
            'search' => ['donor_no', 'name', 'phone', 'email'],
            'columns' => ['donor_no' => 'No. Donatur', 'name' => 'Nama', 'donor_type' => 'Jenis', 'status' => 'Status'],
            'fields' => [
                'donor_no' => ['label' => 'Nomor Donatur', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama Donatur', 'type' => 'text', 'required' => true],
                'donor_type' => ['label' => 'Jenis Donatur', 'type' => 'select', 'options' => ['Perorangan', 'Perusahaan', 'Komunitas', 'Anonim'], 'required' => true],
                'phone' => ['label' => 'Telepon', 'type' => 'text'],
                'email' => ['label' => 'Email', 'type' => 'email'],
                'address' => ['label' => 'Alamat', 'type' => 'textarea'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Aktif', 'Tidak Aktif'], 'required' => true],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'donations' => [
            'title' => 'Donasi', 'icon' => '💝', 'table' => 'donations',
            'search' => ['receipt_no', 'donor_name', 'purpose', 'status'],
            'columns' => ['receipt_no' => 'No. Kuitansi', 'donor_name' => 'Donatur', 'donation_date' => 'Tanggal', 'amount' => 'Nominal', 'status' => 'Status'],
            'money' => ['amount'],
            'fields' => [
                'receipt_no' => ['label' => 'Nomor Kuitansi', 'type' => 'text', 'required' => true],
                'donor_name' => ['label' => 'Nama Donatur', 'type' => 'text', 'required' => true],
                'donation_date' => ['label' => 'Tanggal Donasi', 'type' => 'date', 'required' => true],
                'amount' => ['label' => 'Nominal', 'type' => 'number', 'required' => true],
                'payment_method' => ['label' => 'Metode Pembayaran', 'type' => 'select', 'options' => ['Tunai', 'Transfer Bank', 'QRIS', 'Lainnya'], 'required' => true],
                'purpose' => ['label' => 'Tujuan Donasi', 'type' => 'text'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Menunggu Verifikasi', 'Terverifikasi', 'Dibatalkan'], 'required' => true],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'beneficiaries' => [
            'title' => 'Penerima Manfaat', 'icon' => '🫶', 'table' => 'beneficiaries',
            'search' => ['beneficiary_no', 'name', 'phone', 'need_type'],
            'columns' => ['beneficiary_no' => 'No. Penerima', 'name' => 'Nama', 'need_type' => 'Kebutuhan', 'verification_status' => 'Verifikasi'],
            'fields' => [
                'beneficiary_no' => ['label' => 'Nomor Penerima', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama', 'type' => 'text', 'required' => true],
                'identity_no' => ['label' => 'Nomor Identitas', 'type' => 'text'],
                'phone' => ['label' => 'Telepon', 'type' => 'text'],
                'address' => ['label' => 'Alamat', 'type' => 'textarea'],
                'economic_condition' => ['label' => 'Kondisi Ekonomi', 'type' => 'textarea'],
                'need_type' => ['label' => 'Jenis Kebutuhan', 'type' => 'text', 'required' => true],
                'family_members' => ['label' => 'Jumlah Anggota Keluarga', 'type' => 'number'],
                'verification_status' => ['label' => 'Status Verifikasi', 'type' => 'select', 'options' => ['Belum Disurvei', 'Disurvei', 'Terverifikasi', 'Ditolak'], 'required' => true],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'programs' => [
            'title' => 'Program Sosial', 'icon' => '🌏', 'table' => 'social_programs',
            'search' => ['program_code', 'name', 'category', 'location', 'status'],
            'columns' => ['program_code' => 'Kode', 'name' => 'Program', 'start_date' => 'Tanggal', 'location' => 'Lokasi', 'status' => 'Status'],
            'money' => ['budget'],
            'fields' => [
                'program_code' => ['label' => 'Kode Program', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama Program', 'type' => 'text', 'required' => true],
                'category' => ['label' => 'Kategori', 'type' => 'select', 'options' => ['Pembagian Sembako', 'Donor Darah', 'Bantuan Pendidikan', 'Bantuan Lansia', 'Bantuan Bencana', 'Pemeriksaan Kesehatan', 'Lainnya'], 'required' => true],
                'start_date' => ['label' => 'Tanggal Mulai', 'type' => 'date', 'required' => true],
                'end_date' => ['label' => 'Tanggal Selesai', 'type' => 'date'],
                'location' => ['label' => 'Lokasi', 'type' => 'text'],
                'target_beneficiaries' => ['label' => 'Target Penerima', 'type' => 'number'],
                'budget' => ['label' => 'Anggaran', 'type' => 'number'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Direncanakan', 'Berjalan', 'Selesai', 'Dibatalkan'], 'required' => true],
                'description' => ['label' => 'Deskripsi', 'type' => 'textarea'],
            ],
        ],
        'distributions' => [
            'title' => 'Penyaluran Bantuan', 'icon' => '📦', 'table' => 'assistance_distributions',
            'search' => ['distribution_no', 'program_name', 'beneficiary_name', 'assistance_type'],
            'columns' => ['distribution_no' => 'Nomor', 'distribution_date' => 'Tanggal', 'program_name' => 'Program', 'beneficiary_name' => 'Penerima', 'total_value' => 'Nilai'],
            'money' => ['total_value'],
            'fields' => [
                'distribution_no' => ['label' => 'Nomor Penyaluran', 'type' => 'text', 'required' => true],
                'distribution_date' => ['label' => 'Tanggal', 'type' => 'date', 'required' => true],
                'program_name' => ['label' => 'Program', 'type' => 'text', 'required' => true],
                'beneficiary_name' => ['label' => 'Penerima', 'type' => 'text', 'required' => true],
                'assistance_type' => ['label' => 'Jenis Bantuan', 'type' => 'text', 'required' => true],
                'quantity' => ['label' => 'Jumlah', 'type' => 'number'],
                'total_value' => ['label' => 'Nilai Bantuan', 'type' => 'number', 'required' => true],
                'location' => ['label' => 'Lokasi', 'type' => 'text'],
                'officer_name' => ['label' => 'Petugas', 'type' => 'text'],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'finances' => [
            'title' => 'Keuangan', 'icon' => '💰', 'table' => 'finances',
            'search' => ['transaction_no', 'category', 'description', 'reference_no', 'status'],
            'columns' => ['transaction_no' => 'Nomor', 'transaction_date' => 'Tanggal', 'type' => 'Jenis', 'category' => 'Kategori', 'amount' => 'Nominal', 'status' => 'Status'],
            'money' => ['amount'],
            'fields' => [
                'transaction_no' => ['label' => 'Nomor Transaksi', 'type' => 'text', 'required' => true],
                'transaction_date' => ['label' => 'Tanggal', 'type' => 'date', 'required' => true],
                'type' => ['label' => 'Jenis', 'type' => 'select', 'options' => ['Pemasukan', 'Pengeluaran'], 'required' => true],
                'category' => ['label' => 'Kategori', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Keterangan', 'type' => 'textarea', 'required' => true],
                'amount' => ['label' => 'Nominal', 'type' => 'number', 'required' => true],
                'payment_method' => ['label' => 'Metode Pembayaran', 'type' => 'select', 'options' => ['Tunai', 'Transfer Bank', 'QRIS', 'Lainnya']],
                'reference_no' => ['label' => 'Nomor Referensi', 'type' => 'text'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Draft', 'Diajukan', 'Disetujui', 'Dibayar', 'Selesai', 'Dibatalkan'], 'required' => true],
            ],
        ],
        'volunteers' => [
            'title' => 'Relawan', 'icon' => '🙋', 'table' => 'volunteers',
            'search' => ['volunteer_no', 'name', 'phone', 'skills'],
            'columns' => ['volunteer_no' => 'No. Relawan', 'name' => 'Nama', 'phone' => 'Telepon', 'skills' => 'Keahlian', 'status' => 'Status'],
            'fields' => [
                'volunteer_no' => ['label' => 'Nomor Relawan', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama', 'type' => 'text', 'required' => true],
                'phone' => ['label' => 'Telepon', 'type' => 'text'],
                'email' => ['label' => 'Email', 'type' => 'email'],
                'skills' => ['label' => 'Keahlian', 'type' => 'textarea'],
                'availability' => ['label' => 'Ketersediaan', 'type' => 'text'],
                'service_hours' => ['label' => 'Jam Pengabdian', 'type' => 'number'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Aktif', 'Tidak Aktif'], 'required' => true],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'moral_classes' => [
            'title' => 'Pendidikan Moral', 'icon' => '📚', 'table' => 'moral_classes',
            'search' => ['class_code', 'title', 'teacher_name', 'age_group', 'status'],
            'columns' => ['class_code' => 'Kode', 'title' => 'Materi', 'class_date' => 'Tanggal', 'teacher_name' => 'Pengajar', 'status' => 'Status'],
            'fields' => [
                'class_code' => ['label' => 'Kode Kelas', 'type' => 'text', 'required' => true],
                'title' => ['label' => 'Judul Materi', 'type' => 'text', 'required' => true],
                'class_date' => ['label' => 'Tanggal', 'type' => 'date', 'required' => true],
                'teacher_name' => ['label' => 'Pengajar', 'type' => 'text'],
                'age_group' => ['label' => 'Kelompok Usia', 'type' => 'text'],
                'participant_count' => ['label' => 'Jumlah Peserta', 'type' => 'number'],
                'location' => ['label' => 'Lokasi', 'type' => 'text'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Direncanakan', 'Selesai', 'Dibatalkan'], 'required' => true],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'culture' => [
            'title' => 'Kegiatan Budaya', 'icon' => '🏮', 'table' => 'cultural_activities',
            'search' => ['activity_code', 'title', 'category', 'location', 'status'],
            'columns' => ['activity_code' => 'Kode', 'title' => 'Kegiatan', 'activity_date' => 'Tanggal', 'category' => 'Kategori', 'status' => 'Status'],
            'fields' => [
                'activity_code' => ['label' => 'Kode Kegiatan', 'type' => 'text', 'required' => true],
                'title' => ['label' => 'Nama Kegiatan', 'type' => 'text', 'required' => true],
                'activity_date' => ['label' => 'Tanggal', 'type' => 'date', 'required' => true],
                'category' => ['label' => 'Kategori', 'type' => 'text', 'required' => true],
                'location' => ['label' => 'Lokasi', 'type' => 'text'],
                'participant_count' => ['label' => 'Jumlah Peserta', 'type' => 'number'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Direncanakan', 'Berjalan', 'Selesai', 'Dibatalkan'], 'required' => true],
                'description' => ['label' => 'Deskripsi', 'type' => 'textarea'],
            ],
        ],
        'inventory' => [
            'title' => 'Inventaris', 'icon' => '📋', 'table' => 'inventory_items',
            'search' => ['item_code', 'name', 'category', 'location', 'condition_status'],
            'columns' => ['item_code' => 'Kode', 'name' => 'Barang', 'category' => 'Kategori', 'stock' => 'Stok', 'condition_status' => 'Kondisi'],
            'fields' => [
                'item_code' => ['label' => 'Kode Barang', 'type' => 'text', 'required' => true],
                'name' => ['label' => 'Nama Barang', 'type' => 'text', 'required' => true],
                'category' => ['label' => 'Kategori', 'type' => 'text'],
                'stock' => ['label' => 'Stok', 'type' => 'number', 'required' => true],
                'unit' => ['label' => 'Satuan', 'type' => 'text'],
                'location' => ['label' => 'Lokasi Penyimpanan', 'type' => 'text'],
                'condition_status' => ['label' => 'Kondisi', 'type' => 'select', 'options' => ['Baik', 'Perlu Perbaikan', 'Rusak'], 'required' => true],
                'expiry_date' => ['label' => 'Tanggal Kedaluwarsa', 'type' => 'date'],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
        'documents' => [
            'title' => 'Dokumen dan Surat', 'icon' => '📄', 'table' => 'documents',
            'search' => ['document_no', 'title', 'document_type', 'status'],
            'columns' => ['document_no' => 'Nomor', 'title' => 'Judul', 'document_type' => 'Jenis', 'document_date' => 'Tanggal', 'status' => 'Status'],
            'fields' => [
                'document_no' => ['label' => 'Nomor Dokumen', 'type' => 'text', 'required' => true],
                'title' => ['label' => 'Judul', 'type' => 'text', 'required' => true],
                'document_type' => ['label' => 'Jenis Dokumen', 'type' => 'select', 'options' => ['Surat Masuk', 'Surat Keluar', 'Legalitas', 'Proposal', 'LPJ', 'Perjanjian', 'Lainnya'], 'required' => true],
                'document_date' => ['label' => 'Tanggal Dokumen', 'type' => 'date'],
                'expiry_date' => ['label' => 'Tanggal Berakhir', 'type' => 'date'],
                'file_reference' => ['label' => 'Referensi File/URL', 'type' => 'text'],
                'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Aktif', 'Arsip', 'Berakhir'], 'required' => true],
                'notes' => ['label' => 'Catatan', 'type' => 'textarea'],
            ],
        ],
    ],
];
